### ISSUE TITLE
Add error nodeset per service in summary output

### ISSUE THREAD

**Issue by wilfriedroset** [cea-hpc/milkcheck#25]
Currently the output of milkcheck (with the summary flag) looks like this:

<pre>
[root@nikka1 conf]# milkcheck -c . status --summary
status ping ran in 3.05 s
 > localhost: nikka2
 > localhost: nikka3
 > localhost: nikka5
 > localhost: nikka7
 > localhost: nikka8
 > localhost: nikka11
 > localhost: nikka12
 > localhost: nikka14
 > localhost: nikka15
 > localhost: nikka16
 > localhost exited with 1
ping - Ping all needed servers                                                                             [  ERROR  ]                                                                                          

 SUMMARY - 1 action (1 failed)
 + ping.status - Ping all needed servers                                                         
</pre>

This output doesn't provide easy to read failed targets (nodes) per service.
IMHO, the output would be better like this:

<pre>
[root@nikka1 conf]# milkcheck -c . status --summary
status ping ran in 3.05 s
 > localhost: nikka2
 > localhost: nikka3
 > localhost: nikka5
 > localhost: nikka7
 > localhost: nikka8
 > localhost: nikka11
 > localhost: nikka12
 > localhost: nikka14
 > localhost: nikka15
 > localhost: nikka16
 > localhost exited with 1
ping - Ping all needed servers                                                                             [  ERROR  ]                                                                                          

 SUMMARY - 1 action (1 failed)
 + ping.status - Ping all needed servers
       nikka[0-1,4,6,9-11,13]                                                                             [NOK]
</pre>

**Comment by degremont** [comment]
Could you post the  configuration you used for this test?

**Comment by wilfriedroset** [comment]
From conf/samples/example.yaml
<pre>
[root@nikka1 conf]# cat milkcheck.yaml 
services:
    ping:
        desc: Ping all needed servers
        mode: delegate
        target: "nikka[0-16]"
        actions:
            status:
                cmd: nodeset -S "\n" -e %TARGET | fping -r1 -u
            power:
                cmd: ipmipower -h %TARGET --stat

</pre>

**Comment by degremont** [comment]
In this case, Milkcheck has no clue to guess that some nodes failed and other ran fine.
delegate mode run an external command and milkcheck could not know what is really done by it.

**Comment by degremont** [comment]
However this could be done for regular services.

**Comment by degremont** [comment]
Closed by e5f60cf781a1e2e9d7210086547248c095a2f940
