### ISSUE TITLE
Milkcheck should be failure tolerant

### ISSUE THREAD

**Issue by wilfriedroset** [cea-hpc/milkcheck#28]
When at least one target of a service is failed the service is tagged as *ERROR* and all dependencies are skipped even on the targets that have succeed. The user then need to exclude the failed targets and rerun the Milkcheck command.

Milkcheck should provide 2 behaviours:

- All targets need to succeed in order to run dependency
- Excluded failed targets and proceed on the others (advise the user in the summary of the failed targets)

**Comment by degremont** [comment]
Duplicate of #6 .
