### ISSUE TITLE
ERROR    - Bad entry 'summary'

### ISSUE THREAD

**Issue by actatux** [cea-hpc/milkcheck#37]
After upgrading from 1.0 to 1.1, milkcheck fails.

Indeed, the commit e5f60cf7 removes the `summary` parameter. However, the specfile does not replace the configuration file, thus the parameter still exists and cannot be processed.

```
# cat /etc/milkcheck/milkcheck.conf

# Configuration directory
# This directory should contain yaml configuration files
config_dir: /etc/milkcheck/conf

# Default fanout connection for any service
fanout: 32

# Don't display summary by default (True/False)
summary: False

# Actions that reverse the dependencies constraints (default 'stop')
reverse_actions: [ 'stop' ]

# milkcheck --version
milkcheck 1.0
# yum update milkcheck -y
# milkcheck --version
milkcheck 1.1
# milkcheck
[17:04:04] ERROR    - Bad entry 'summary'
```
It would have been great to add some deprecation notice.

**Comment by degremont** [comment]
Actually this is bug. There is a fix underway for that

The line   
```
       'summary':         { 'value': False, 'type': bool },
```
is missing from `ConfigParser.py`

This option is deprecated but still supported.
