### ISSUE TITLE
Version RHEL8?

### ISSUE THREAD

**Issue by MarbolanGos** [cea-hpc/milkcheck#55]
Hello,
I would like to know if there is a version for RHEL8/CentOS8 available for milkcheck. I would like to use it but I was unable to recompile it from sources, it displays errors with python:
```make
# make rpm
git archive --prefix=milkcheck-1.2.3/ HEAD | gzip -9 >milkcheck-1.2.3.tar.gz
mkdir -p $PWD/RPMBUILD/{BUILD,RPMS,SRPMS,SPECS}
a2x -f manpage doc/milkcheck.asciidoc
rpmbuild --define "_topdir $PWD/RPMBUILD" --define "_sourcedir $PWD" -ba milkcheck.spec
error: attempt to use unversioned python, define %__python to /usr/bin/python2 or /usr/bin/python3 explicitly
error: line 32: make install DESTDIR="%{buildroot}" PYTHON=%{__python} MANDIR=%{_mandir} \
             SYSCONFIGDIR=%{_sysconfdir} VIMDATADIR=%{vimdatadir}

make: *** [Makefile:37: rpm] Error 1
```

**Comment by MarbolanGos** [comment]
Hi,
Do you have update on this?
Regards,

**Comment by oxedions** [comment]
I am also interested by an Python 3 based version, for our opensource stack [bluebanquise](https://github.com/bluebanquise/bluebanquise)

**Comment by cedeyn** [comment]
Hi,
First sorry for the delay, but I didn't forget this request :)
It looks like the specfile was not correctly updated with my last commit.
A fix is coming soon.

**Comment by cedeyn** [comment]
Hi, #56 should fix this issue.
Could you try and confirm it solves this issue ?

**Comment by MarbolanGos** [comment]
Hello,

Thank you for the patch, I pulled it and run it on RHEL8 and it worked. At the end I have the RPM available:
`# ls RPMBUILD/RPMS/noarch/milkcheck-*
RPMBUILD/RPMS/noarch/milkcheck-1.2.4-1.el8.noarch.rpm` 

Many thanks for this product.

**Comment by cedeyn** [comment]
Great, new release is coming.

**Comment by oxedions** [comment]
Thanks a lot ! 😊
